# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np
np.__version__

'1.24.3'

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
# 创建矩阵 A，包含1到15的元素，然后将其reshape为3行5列的矩阵
A = np.arange(1, 16).reshape(3,5)

In [5]:
# 输出矩阵 A 的维度（轴数）
print("Dimension of A:", A.ndim)

# 输出矩阵 A 的形状（行数，列数）
print("Shape of A:", A.shape)

# 输出矩阵 A 的大小（总元素个数）
print("Size of A:", A.size)

# 输出矩阵 A 中元素的数据类型
print("Data type of A:", A.dtype)

Dimension of A: 2
Shape of A: (3, 5)
Size of A: 15
Data type of A: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
import numpy as np

#定义矩阵 B 和 C 
B = np.arange(1,10).reshape(3,3)
C = np.ones((3,3))*2

# 逐元素相减
elementwise_subtraction = B - C
print("Elementwise Subtraction:")
print(elementwise_subtraction)
print()

# 逐元素相乘
elementwise_multiplication = B * C
print("Elementwise Multiplication:")
print(elementwise_multiplication)
print()

# 使用 @ 运算符进行矩阵乘法
matrix_multiplication = B @ C
print("Matrix Multiplication:")
print(matrix_multiplication)

Elementwise Subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [5]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
import numpy as np

# 定义矩阵 B
B = np.arange(1, 10).reshape(3, 3)
print("Original Matrix B:")
print(B)
print()

# 对矩阵中的每个元素进行指数运算
exponentiated_matrix = np.exp(B)
print("Exponentiated Matrix (elementwise exponentiation):")
print(exponentiated_matrix)
print()

# 计算整个矩阵中的最小值
min_value_whole_matrix = np.min(B)
print("Minimum value in the entire matrix:", min_value_whole_matrix)
print()

# 计算每行中的最小值
min_value_each_row = np.min(B, axis=1)
print("Minimum value in each row:")
print(min_value_each_row)
print()

# 计算每列中的最小值
min_value_each_column = np.min(B, axis=0)
print("Minimum value in each column:")
print(min_value_each_column)
print()

# 找到整个矩阵中最小值的索引
min_value_index_whole_matrix = np.unravel_index(np.argmin(B, axis=None), B.shape)
print("Index of minimum value in the entire matrix:")
print(min_value_index_whole_matrix)
print()

# 找到每行中最小值的索引
min_value_index_each_row = np.argmin(B, axis=1)
print("Indices of minimum values in each row:")
print(min_value_index_each_row)
print()

# 计算矩阵中所有元素的和
sum_of_elements = np.sum(B)
print("Sum of all elements in the matrix:", sum_of_elements)
print()

# 计算每列的平均值
mean_of_each_column = np.mean(B, axis=0)
print("Mean of each column:")
print(mean_of_each_column)
print()

# 计算每列的中位数
median_of_each_column = np.median(B, axis=0)
print("Median of each column:")
print(median_of_each_column)


Original Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiated Matrix (elementwise exponentiation):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the entire matrix: 1

Minimum value in each row:
[1 4 7]

Minimum value in each column:
[1 2 3]

Index of minimum value in the entire matrix:
(0, 0)

Indices of minimum values in each row:
[0 0 0]

Sum of all elements in the matrix: 45

Mean of each column:
[4. 5. 6.]

Median of each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [11]:
# 创建矩阵 A，包含1到15的元素，然后将其reshape为3行5列的矩阵
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [12]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [12]:
import numpy as np

# 定义一个二维数组A
A = np.arange(1, 16).reshape(3, 5)

# 打印整个数组A
print("Entire Array A:")
print(A)
print()

# 使用少于数组轴数的索引进行切片，返回第二行
second_row = A[1]

# 打印第二行
print("Second Row:")
print(second_row)


Entire Array A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Second Row:
[ 6  7  8  9 10]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [7]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [4]:
import numpy as np

# 定义一个二维数组 A
A = np.arange(1, 16).reshape(3, 5)

# 逐个元素地迭代数组
for row in A:
    for element in row:
        print(element)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [5]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30): 这行代码创建了一个包含0到29之间整数的一维NumPy数组a。np.arange(30)函数生成一个包含0到29之间整数的数组。

b = a.reshape((2, 3, -1)): 这里，reshape()函数用于将一维数组a重新塑形为三维数组b。b的形状被指定为(2, 3, -1)。形状参数中的-1是一个占位符，
    它表示NumPy应该根据原始数组的大小和其他指定的维度自动计算该维度的大小。在这种情况下，-1将被替换为5，因为原始数组a有30个元素，
    而其他两个维度（2和3）总共有6个元素。所以，5是第三个维度的大小，得到的三维数组形状为(2, 3, 5)。

print(a): 这行代码打印原始的一维数组a。

print(b): 这行代码打印重新塑形后的三维数组b。

在NumPy数组的背景下，“轴”指的是数组的维度。在这种情况下，数组b有三个轴：

第一个轴（轴0）：它的大小为2，表示有2个数据块。
第二个轴（轴1）：它的大小为3，表示每个数据块内有3行。
第三个轴（轴2）：它的大小为5，表示每个数据块内的每行有5列。
在这三维数组b中，每个元素由其在这三个轴上的索引唯一确定。例如，b[0, 1, 2]表示数组b中第一个数据块（轴0）、第二行（轴1）和第三列（轴2）的元素。






### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [13]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

print(m1.shape)
print(m2.shape)

[[2 3]
 [4 5]]
(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [15]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [14]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print()

print(A+b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [17]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [22]:
def add_mult_matrices(A, B, add_or_multiply):
    
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise Exception('Please provide two matrices.')
    
    if add_or_multiply == 'add':
        if not A.shape == B.shape:
            raise ValueError('Same shape required for matrix addition.')
        else: 
            return A + B
        
    elif add_or_multiply == 'multiply':
        if not A.shape[1] == B.shape[0]:
            raise ValueError('Columns and rows must be the shame length in matrix multiplicatio')
        else:
            return A @ B
        
    else:
        raise Exception('the add_or_multiply argument must be "add" or "multiply". ')
        

# B - 2A
add_mult_matrices(B, -2*A, 'add')  # Notice must take -2*A since subtraction is addition with a negative sign. 

array([[ 0, -3],
       [-3, -5]])

In [24]:
# 3C - E
add_mult_matrices(3*C, -E, 'add')

NameError: name 'E' is not defined

In [25]:
# AC
add_mult_matrices(A, C, 'multiply')

array([[ 4,  7],
       [ 8, 14]])

In [26]:
# CD
add_mult_matrices(C, D, 'multiply')

NameError: name 'D' is not defined

In [27]:
# CB
add_mult_matrices(C, B, 'multiply')

array([[11, 13],
       [ 2,  6]])

**Chap2. Question 2**

In [17]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

print('AB:', '\n', AB)
print('AC:', '\n', AC)

# AB = AC yet B is not equal to C.
print((AB == AC).all())  
print((B == C).all())  


AB: 
 [[ 2  2]
 [ 2 12]]
AC: 
 [[4 6]
 [0 8]]
False
False


In [19]:
print('AB:', '\n', add_mult_matrices(A, B, 'multiply'))
print('AC:', '\n', add_mult_matrices(A, C, 'multiply'))

AB: 
 [[ 2  2]
 [ 2 12]]
AC: 
 [[4 6]
 [0 8]]


**Chap2. Question 3**

In [28]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print('AD:', '\n', add_mult_matrices(A, D, 'multiply'))
print('DA', '\n', add_mult_matrices(D, A, 'multiply'))

AD: 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
DA 
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [29]:
M1 = np.array([[1, -1], [-1, 1]])
M2 = np.array([[-1, 1], [1, -1]])

print('M1M2', '\n', add_mult_matrices(M1, M2, 'multiply'))

M1M2 
 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [31]:
M1 = np.array([[5, 6], [4, 5]])
M2 = np.array([[6, 4], [3, 3]])

M1_inv = np.linalg.inv(M1)
print(M1_inv)

# Check if M1 @ M1_inv is the identity matrix (due to round-off error in the PC, we use np.allclose.)
print(M1 @ M1_inv)
print(np.allclose(M1 @ M1_inv, np.eye(2)))

[[ 5. -6.]
 [-4.  5.]]
[[ 1.00000000e+00  0.00000000e+00]
 [-3.55271368e-15  1.00000000e+00]]
True


In [32]:
M2_inv = np.linalg.inv(M2)
print(M2_inv)

# Check if M1 @ M1_inv is the identity matrix (due to round-off error in the PC, we use np.allclose.)
print(M2 @ M2_inv)
print(np.allclose(M2 @ M2_inv, np.eye(2)))

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]
[[1. 0.]
 [0. 1.]]
True


**Quiz p.19, Question 3**

In [32]:
M = np.array([[2, 2], [1, 2]])
M_inv = np.linalg.inv(M)
print(M_inv)

print(M @ M_inv)
print(np.allclose(M @ M_inv, np.eye(2)))

[[ 1.  -1. ]
 [-0.5  1. ]]
[[1. 0.]
 [0. 1.]]
True


**Chap10. Question 1 a)**

In [36]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])
print(A)
print(b)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]
[-7  5  2]


In [37]:
# The solution to the system of equations.
x = np.linalg.solve(A, b)
print(x)

[ 3.  4. -6.]


In [38]:
# Double check if Ax = b.
A @ x

array([-7.,  5.,  2.])

**Chap10. Question 1 b)**

In [38]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

In [40]:
# The solution to the system of equations.
x = np.linalg.solve(A, b)
print(x)

[ 8.  2. -1.]


In [41]:
# Double check if Ax = b.
A @ x

array([ 1., -1.,  1.])

**Chap 12. Question 1**

In [43]:
M = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
M_inv = np.linalg.inv(M)
print(M_inv)

# Check if M1 @ M1_inv is the identity matrix (due to round-off error in the PC, we use np.allclose.)
# print(M @ M_inv)
print(np.allclose(M @ M_inv, np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [44]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [45]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [46]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
